# File: .github/workflows/workflow.yml

on: [push]

name: Azure KeyVault using azure/get-keyvault-secrets@release-stack

env:
  NUGET_VERSION: '5.3.1'                # set this to the node version to use
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@releases/v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: AzureCloud
    - uses: azure/get-keyvault-secrets@release-stack
      with:
        keyvault: "ghakeyvault"
        secrets: 'secret001'  # comma separated list of secret keys that need to be fetched from the Key Vault 
      id: myGetSecretAction