# File: .github/workflows/workflow.yml

on: [push]

name: AzureStack KeyVault azurestack-v1 branch

env:
  NUGET_VERSION: '5.3.1'                # set this to the node version to use
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build:
    runs-on: self-hosted
    steps:
    # checkout the repo
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Use Private Azure Login Action
      uses: azure/login@releases/v1
      with:
        creds: ${{ secrets.AZURESTACK_ORLANDO }}
        environment: azurestack
    - name: Use KeyVault Action Test branch
      uses: rakku-ms/get-keyvault-secrets@azurestack-v1
      with:
        keyvault: ghakeyvault
        secrets: 'secret001'  # comma separated list of secret keys that need to be fetched from the Key Vault 
      id: myGetSecretAction